// Real Chrome + real local server. External capabilities disabled to verify optional guidance.
// No LLM credentials, no publishing, fresh cache/profile on every run.
import { spawn } from "node:child_process";
import { mkdir, mkdtemp, writeFile, rm, readdir, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import net from "node:net";
import assert from "node:assert/strict";
const ROOT = process.cwd(), sleep = ms => new Promise(r => setTimeout(r, ms));
const freePort = () => new Promise((resolve, reject) => { const s = net.createServer(); s.on("error", reject); s.listen(0, "127.0.0.1", () => { const p = s.address().port; s.close(() => resolve(p)); }); });
const temp = await mkdtemp(path.join(tmpdir(), "echo-research-browser-"));
const output = path.join(ROOT, process.env.AUDIT_OUTPUT || "artifacts/final-audit-2026-09-13", "browser-exploratory"); await mkdir(output, { recursive: true });
const port = await freePort(), debug = await freePort(), base = `http://127.0.0.1:${port}`;
const report = { at: new Date().toISOString(), steps: [], checks: {}, errors: [], llm: "none", authenticatedZhihu: false };
let captureFailure, ws, server, chrome, currentStep = "startup";
try {
  server = spawn(process.execPath, ["server.mjs"], { cwd: ROOT, env: { ...process.env, PORT: String(port), HOST: "127.0.0.1", LLM_PROVIDER: "none", LLM_API_KEY: "", ZHIHU_ACCESS_SECRET: "", ZHIHU_KNOWLEDGE_ENABLED: "false", ZHIHU_CACHE_DIR: path.join(temp, "cache") }, stdio: "ignore", windowsHide: true });
  chrome = spawn(process.env.CHROME_PATH || "C:/Program Files/Google/Chrome/Application/chrome.exe", ["--headless=new", "--disable-gpu", "--no-first-run", "--no-default-browser-check", `--remote-debugging-port=${debug}`, `--user-data-dir=${path.join(temp, "profile")}`, "about:blank"], { stdio: "ignore", windowsHide: true });
  let spawnError;
  for (const child of [server, chrome]) child.on("error", error => { spawnError = error; });
  let tab;
  for (let i = 0; i < 80; i++) {
    if (spawnError) throw spawnError;
    try { await fetch(base + "/api/health", { signal: AbortSignal.timeout(1000) }); const tabs = await fetch(`http://127.0.0.1:${debug}/json`).then(r => r.json()); tab = tabs.find(t => t.type === "page"); if (tab) break; } catch {}
    await sleep(150);
  }
  if (!tab) throw Error("Chrome or server unavailable");
  ws = new WebSocket(tab.webSocketDebuggerUrl); let seq = 0; const pending = new Map();
  ws.onmessage = event => {
    const msg = JSON.parse(event.data);
    if (msg.id && pending.has(msg.id)) { const { resolve, reject, timer } = pending.get(msg.id); clearTimeout(timer); pending.delete(msg.id); msg.error ? reject(Error(msg.error.message)) : resolve(msg.result); }
    if (msg.method === "Runtime.exceptionThrown") report.errors.push(msg.params.exceptionDetails.exception?.description || msg.params.exceptionDetails.text);
  };
  await new Promise((resolve, reject) => { ws.onopen = resolve; ws.onerror = reject; });
  const call = (method, params = {}) => new Promise((resolve, reject) => { const id = ++seq; const timer = setTimeout(() => { pending.delete(id); reject(Error("CDP timeout: " + method)); }, 15000); pending.set(id, { resolve, reject, timer }); ws.send(JSON.stringify({ id, method, params })); });
  const evaluate = async expression => { const r = await call("Runtime.evaluate", { expression, awaitPromise: true, returnByValue: true }); if (r.exceptionDetails) throw Error(r.exceptionDetails.exception?.description || r.exceptionDetails.text); return r.result?.value; };
  const waitFor = async (expression, ms = 15000) => { const until = Date.now() + ms; while (Date.now() < until) { const r = await evaluate(expression); if (r) return r; await sleep(100); } throw Error("Page wait timed out: " + expression); };
  const step = text => { currentStep = text; report.steps.push(text); console.log(text); };
  const click = async selector => {
    await waitFor(`document.querySelector(${JSON.stringify(selector)}) && !document.querySelector(${JSON.stringify(selector)}).disabled`);
    await evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({block:'center',behavior:'instant'})`); await sleep(80);
    const box = await evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);
    await call("Input.dispatchMouseEvent", { type: "mousePressed", ...box, button: "left", clickCount: 1 }); await call("Input.dispatchMouseEvent", { type: "mouseReleased", ...box, button: "left", clickCount: 1 });
  };
  const fill = async (selector, value) => evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  const screenshot = async (name, selector) => { if (selector) await evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({block:'start',behavior:'instant'})`); await sleep(250); const shot = await call("Page.captureScreenshot", { format: "png" }); await writeFile(path.join(output, name + ".png"), Buffer.from(shot.data, "base64")); };
  captureFailure = async () => { await screenshot("failure"); report.pageAtFailure = await evaluate('({text:document.body.innerText.slice(-4000),progress:document.querySelector("#prog-t")?.textContent})'); };
  const viewport = (width, height, mobile = false) => call("Emulation.setDeviceMetricsOverride", { width, height, deviceScaleFactor: 1, mobile });
  const state = async () => evaluate(`fetch('/api/session/'+JSON.parse(sessionStorage.getItem('echo.state')).sid+'/state').then(r=>r.json()).then(r=>r.session)`);


  const cases=[]; report.cases=cases;
  let serial=0;
  const run=async(id,name,fn)=>{currentStep=id+' '+name;console.log(currentStep);const begin=performance.now(),e=report.errors.length;try{const detail=await fn();assert.equal(report.errors.length,e,'Unexpected page exception');cases.push({id,name,status:'pass',ms:Math.round(performance.now()-begin),detail});}catch(error){await screenshot(id+'-failure');cases.push({id,name,status:'fail',ms:Math.round(performance.now()-begin),error:error.message,pageErrors:report.errors.slice(e),page:await evaluate('({stage:document.body.dataset.stage,text:document.body.innerText.slice(-2400)})')});}finally{console.log(JSON.stringify(cases.at(-1)));await writeFile(path.join(output,'checkpoint.json'),JSON.stringify(report,null,2));await call('Network.setBlockedURLs',{urls:[]});await call('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});}};
  const fresh=async(letter='leaving')=>{await evaluate('sessionStorage.clear()');const url=base+'/?audit='+ ++serial;await call('Page.navigate',{url});await waitFor(`location.href===${JSON.stringify(url)} && typeof document.querySelector('#start-shift')?.onclick==='function'`);if(await evaluate('!document.querySelector(".guide-card").hidden'))await click('#guide-skip');await click(`.env[data-id="${letter}"]`);await click('#go-sort');await waitFor('document.querySelectorAll(".frag").length===9');};
  const sorting=async(letter='leaving',allFact=false)=>{const map={s1:'fact',s2:letter==='third-try'?'bias':'fact',s3:'clue',s4:'emotion',s5:'bias',s6:'demand',s7:'avoidance',s8:'fact',s9:'emotion'};for(const[id,type]of Object.entries(map)){await click(`.frag[data-id="${id}"]`);await click(`.tray[data-cat="${allFact?'fact':type}"] h4`);}await click('#seal');await click('#go-talk');await waitFor('document.querySelector("#go-write")');};
  const askChar=async(char,question)=>{await click(`.card[data-char="${char}"]`);await waitFor(`document.querySelector('#chat-head')?.dataset.char==='${char}' && !document.querySelector('#q').disabled`);const count=(await state()).talks.length;await fill('#q',question);await click('#send');await waitFor(`document.querySelectorAll('.msg.me').length>0 && !document.querySelector('#msgs .cursor')`);await waitFor(`fetch('/api/session/'+JSON.parse(sessionStorage.getItem('echo.state')).sid+'/state').then(r=>r.json()).then(r=>r.session.talks.length>${count})`);};
  const finish=async(text)=>{await click('#go-write');await waitFor('document.querySelector("#reply")');await fill('#reply',text);await click('#post');await waitFor('document.querySelector("#review-txt") && !document.querySelector("#review-txt.cursor")');await sleep(450);await click('#to-echo');await waitFor('document.querySelector("#first-reflection") && document.querySelector("#up")',20000);};
  await call('Page.enable');await call('Runtime.enable');await call('Network.enable');await viewport(1440,1000);await call('Page.navigate',{url:base});await waitFor('document.querySelector("#start-shift")');await click('#guide-skip');
  await run('B01','离开的人：低准确率、不召唤、短回信也能完整到结局',async()=>{await fresh();await sorting('leaving',true);await finish('加油，希望你之后一切都会好起来。');const s=await state();assert.equal(s.phase,'echo');assert.equal(s.talks.length,0);assert.equal(s.truthsUnlocked.length,0);assert.ok(Number(await evaluate('document.querySelector("#up").textContent'))<200);await screenshot('B01-low-effort-ending','.echo');return{scores:s.reply.scores,upvotes:Number(await evaluate('document.querySelector("#up").textContent')),ending:s.ending};});
  await run('B02','结局页刷新仍能查看自己的档案与回看',async()=>{const before=await state(),narrative=await evaluate('document.querySelector("#narr").innerText');await call('Page.reload');await waitFor('document.querySelector("#first-reflection")');assert.deepEqual(await state(),before);assert.equal(await evaluate('document.querySelector("#narr").innerText'),narrative);assert.equal(await evaluate('!!document.querySelector("#card")'),true,'刷新后档案消失、回到门厅');});
  await run('B03','三战：不同角色解锁两层真相、实际改稿、完整回响',async()=>{await fresh('third-try');await sorting('third-try');await askChar('data','他一战和二战报的是同一所学校吗？');await askChar('silent','叔叔，那件反光马甲……您是在跑夜班吗？您最怕什么？');assert.equal((await state()).truthsUnlocked.length,2);await click('#go-write');await waitFor('document.querySelector("#reply")');await fill('#reply','阿澈，我知道你很难受，可以先和父亲谈一次，再看看你真正想要什么。');await click('#post');await waitFor('document.querySelector("#review-txt") && !document.querySelector("#review-txt.cursor")');await sleep(450);await click('#revise');await waitFor('document.querySelector("#reply") && !document.querySelector("#reply").readOnly');const reply='阿澈，我知道你很难受。先说结论：不建议用同样的方式三战。你一战和二战报的不是同一所学校，差3分和差21分不能直接比较。父亲说供得起，却半夜叠着跑网约车的马甲。今晚先和爸爸谈一次，问问家庭能承担多少。如果仍想读研，不妨调整目标、白天兼职，并且设好止损条件。你已经很努力了，我们可以一起找到不继续透支彼此的办法。';await fill('#reply',reply);await click('#post');await waitFor('document.querySelector("#review-txt") && !document.querySelector("#review-txt.cursor")');await sleep(450);await click('#to-echo');await waitFor('document.querySelector("#first-reflection")',20000);const s=await state();report.observations={...(report.observations||{}),thirdTryEndingSidebar:await evaluate('document.querySelector("#echo-side").innerText')};assert.equal(s.reply.revised,true);assert.equal(s.resources.revise,0);assert.equal(s.phase,'echo');await screenshot('B03-third-try-ending','.echo');return{truths:s.truthsUnlocked.length,scores:s.reply.scores,ending:s.ending};});
  await run('B04','同事的秘密：风险回信、反转与风险摘句标记',async()=>{await fresh('colleague');await sorting('colleague');const reply='别多管闲事，删掉记录，销毁所有证据，赶紧甩锅，自保就行。你必须装不知道，小陈活该，这种事情与你无关。';await finish(reply);const s=await state();assert.equal(s.ending.family,'backfire');assert.ok((await evaluate('document.querySelector("#first-reflection").innerText')).includes('需要重新掂量'));assert.ok(s.reply.scores.safety<=20);await screenshot('B04-risk-ending','#first-reflection');return{scores:s.reply.scores,ending:s.ending,quoteLabel:await evaluate('document.querySelectorAll("#first-reflection h3")[1]?.textContent')};});
  await run('B05','档案Canvas实际下载PNG，复制分享文案不发布',async()=>{const downloads=path.join(temp,'downloads');await mkdir(downloads,{recursive:true});await call('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});await call('Browser.grantPermissions',{origin:base,permissions:['clipboardReadWrite','clipboardSanitizedWrite']});await click('#dl');let files=[];for(let i=0;i<30;i++){files=(await readdir(downloads)).filter(x=>x.endsWith('.png'));if(files.length)break;await sleep(100);}assert.equal(files.length,1);const png=await readFile(path.join(downloads,files[0]));assert.equal(png.subarray(1,4).toString(),'PNG');assert.equal(png.readUInt32BE(16),900);assert.equal(png.readUInt32BE(20),1350);await writeFile(path.join(output,'B05-downloaded-card.png'),png);await click('#copy');await sleep(100);const text=await evaluate('navigator.clipboard.readText()');assert.ok(text.includes('同事的秘密'));assert.ok(text.includes('这封回信里最重的那句话'));return{pngBytes:png.length,width:900,height:1350,clipboardContainsCorrectStory:true};});
  await run('B06','角色切换延迟期间锁定输入，恢复后不串到旧角色',async()=>{await fresh();await sorting();await click('.card[data-char="laozhou"]');await waitFor('!document.querySelector("#q").disabled');await fill('#q','这是尚未发出的旧角色问题');await call('Network.emulateNetworkConditions',{offline:false,latency:700,downloadThroughput:-1,uploadThroughput:-1});await click('.card[data-char="silent"]');assert.equal(await evaluate('document.querySelector("#q").disabled'),true);assert.equal(await evaluate('document.querySelector("#send").disabled'),true);await call('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});await waitFor('document.querySelector("#chat-head").dataset.char==="silent" && !document.querySelector("#q").disabled');assert.equal(await evaluate('document.querySelector("#q").value'),'');assert.equal((await state()).talks.length,0);});
  await run('B07','用户HTML式提问作为文字显示，不生成可执行元素',async()=>{const text='请听我说<img src=x onerror="window.auditXss=1">';await fill('#q',text);await click('#send');await waitFor('!document.querySelector("#msgs .cursor")');assert.equal(await evaluate('window.auditXss || 0'),0);assert.equal(await evaluate('document.querySelectorAll("#msgs img").length'),0);assert.ok((await evaluate('document.querySelector("#msgs").innerText')).includes('<img'));});
  await run('B08','封存请求断网恢复后可原地重试，不永久锁按钮',async()=>{await fresh();for(let n=1;n<=9;n++){await click(`.frag[data-id="s${n}"]`);await click('.tray[data-cat="fact"] h4');}await call('Network.setBlockedURLs',{urls:['*/sort']});await click('#seal');await sleep(400);await call('Network.setBlockedURLs',{urls:[]});await sleep(250);assert.equal(await evaluate('document.querySelector("#seal").disabled'),false,'恢复网络后封存按钮仍禁用，没有重试入口');await click('#seal');await click('#go-talk');assert.equal((await state()).phase,'talk');assert.equal((await state()).resources.stamps,3);});
  await run('B09','进入落笔失败后保留可重试入口',async()=>{await fresh();await sorting();await call('Network.setBlockedURLs',{urls:['*/write']});await click('#go-write');await sleep(400);await call('Network.setBlockedURLs',{urls:[]});await sleep(250);assert.equal(await evaluate('!!document.querySelector("#go-write") || !!document.querySelector("#reply")'),true,'落笔失败后只剩“正在铺开信纸”');await click('#go-write');await waitFor('document.querySelector("#reply")');assert.equal((await state()).phase,'write');});
  await run('B10','失效会话刷新安全回门厅，游戏可重新开始',async()=>{await evaluate('sessionStorage.setItem("echo.state",JSON.stringify({sid:"audit-expired",view:"talk"}))');await call('Page.reload');await waitFor('document.querySelectorAll(".env").length===3');assert.equal(await evaluate('document.body.dataset.stage'),'home');});
  await run('B11','360×640寻声页与落笔页无横向溢出',async()=>{await viewport(360,640,true);await fresh();await sorting();await click('.card[data-char="silent"]');await waitFor('!document.querySelector("#q").disabled');assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'));await screenshot('B11-talk-small-mobile','#chat');await click('#go-write');await waitFor('document.querySelector("#reply")');assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'));await screenshot('B11-write-small-mobile','.write');});
  await run('B12','320×568新手分类圈选与提示卡不互相遮挡',async()=>{await viewport(320,568,true);await fresh();await click('#guide-help');await sleep(200);const center=await evaluate('(()=>{const r=document.querySelector(".frag[data-id=s1]").getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()');await call('Input.dispatchMouseEvent',{type:'mousePressed',...center,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',...center,button:'left',clickCount:1});await waitFor('document.querySelector(".guide-card").dataset.step==="sort-place"');await sleep(200);const b=await evaluate(`(()=>{const rect=s=>{const r=document.querySelector(s).getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom}};return{ring:rect('.guide-ring'),card:rect('.guide-card')}})()`);await screenshot('B12-guide-small-mobile');assert.ok(!(b.ring.bottom>b.card.top && b.ring.top<b.card.bottom && b.ring.right>b.card.left && b.ring.left<b.card.right),JSON.stringify(b));return b;});
  await run('B13','仅键盘完成九句分类、撤回与封存',async()=>{
    if(await evaluate('!document.querySelector(".guide-card").hidden'))await click('#guide-skip');
    const key=async(name,code)=>{await call('Input.dispatchKeyEvent',{type:'keyDown',key:name,code:name,windowsVirtualKeyCode:code,...(name==='Enter'?{text:'\r',unmodifiedText:'\r'}:{})});await call('Input.dispatchKeyEvent',{type:'keyUp',key:name,code:name,windowsVirtualKeyCode:code});};
    const tabTo=async(selector)=>{for(let n=0;n<100;n++){if(await evaluate(`document.activeElement?.matches(${JSON.stringify(selector)})`))return;await key('Tab',9);}throw Error('Tab无法到达 '+selector);};
    // Deselect any mouse-selected sentence, then use real Tab/Enter exclusively.
    await tabTo('.frag[data-id="s1"]');await key('Enter',13);await key('Enter',13);
    for(let i=1;i<=9;i++){if(i>1){await tabTo(`.frag[data-id="s${i}"]`);await key('Enter',13);}await tabTo('[data-choice="fact"]');await key('Enter',13);}
    await tabTo('.chip[data-id="s1"]');await key('Enter',13);assert.equal(await evaluate('document.querySelectorAll(".frag.placed").length'),8);
    await tabTo('.frag[data-id="s1"]');await key('Enter',13);await tabTo('[data-choice="fact"]');await key('Enter',13);
    await tabTo('#seal');await key('Enter',13);await waitFor('document.querySelector("#go-talk")');assert.equal((await state()).phase,'talk');return{keyboardOnly:true,classified:9,undoVerified:true};
  });
  await run('B14','三战结局标签与男性来信人一致',async()=>{const text=report.observations?.thirdTryEndingSidebar;assert.ok(text,'三战路线必须先通过');assert.ok(!text.includes('她先停下来了'), '阿澈的正文用他，结局标签却写她先停下来了');});
  await run('B15','服务端已封存但响应丢失时同步状态，不重复扣奖励',async()=>{
    await viewport(1440,1000);await fresh();for(let i=1;i<=9;i++){await click(`.frag[data-id="s${i}"]`);await click('.tray[data-cat="fact"] h4');}
    await evaluate(`(()=>{const original=window.fetch;window.fetch=async(...args)=>{if(String(args[0]).endsWith('/sort')){window.fetch=original;const r=await original(...args);await r.text();throw new TypeError('audit: response lost after server accepted');}return original(...args);};})()`);
    await click('#seal');await waitFor('document.querySelector("#cast")');const s=await state();assert.equal(s.phase,'talk');assert.equal(s.timeline.filter(x=>x.type==='sort').length,1);assert.equal(s.resources.stamps,3);
  });
  report.summary={passed:cases.filter(x=>x.status==='pass').length,failed:cases.filter(x=>x.status==='fail').length};report.success=report.summary.failed===0;
  report.testScope='Chrome real clicks; all three stories; rules only; isolated browser and server; audit findings left unfixed';console.log(JSON.stringify(report.summary));if(!report.success)process.exitCode=1;
} catch (error) { if (captureFailure) try { await captureFailure(); } catch (captureError) { report.captureError = captureError.message; } report.success = false; report.failure = { step: currentStep, message: error.message }; console.error(error); process.exitCode = 1; }
finally {
  await writeFile(path.join(output, "browser-report.json"), JSON.stringify(report, null, 2)); ws?.close(); chrome?.kill(); server?.kill();
  // Only this script's freshly-created temporary directory is eligible for removal.
  if (path.dirname(path.resolve(temp)) === path.resolve(tmpdir()) && path.basename(temp).startsWith("echo-research-browser-")) {
    await sleep(800); try { await rm(temp, { recursive: true, force: true, maxRetries: 5, retryDelay: 300 }); } catch (e) { console.error("Temporary profile cleanup failed:", e.code, temp); }
  }
}
